from components.database.database import *
from components.owner_routes import *
from components.property_routes import *
from components.employee_routes import *
from components.equipment_routes import *
from components.service_routes import *
from components.workorder_routes import *
from components.repair_routes import *
from components.index_routes import *